trigger:
  branches:
    include:
      - main
      - development
  paths:
    exclude:
      - README.md
      - docs/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/development')]
  dockerRegistryServiceConnection: 'your-registry-connection'
  imageRepository: 'system-transport'
  containerRegistry: 'your-registry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'your-azure-subscription'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        echo "📝 Documentation: Setting up Node.js environment"
        echo Node.js and npm versions:
        node -v
        npm -v
        
        echo Installing pnpm...
        npm install -g pnpm
        pnpm --version
      displayName: 'Install pnpm'

    - script: |
        echo "📝 Documentation: Installing project dependencies"
        echo Cleaning existing directories...
        rm -rf node_modules
        rm -rf .next
        
        echo Installing dependencies with pnpm...
        pnpm install --frozen-lockfile
        
        echo Checking installation...
        ls -la node_modules
      displayName: 'Install Dependencies'
      
    - script: |
        echo "📝 Documentation: Running ESLint for code quality"
        echo Running linting with ESLint...
        pnpm lint
      displayName: 'Run ESLint'
      continueOnError: false

    - script: |
        echo "📝 Documentation: Running Jest unit tests"
        echo Running tests with Jest...
        pnpm test:ci
      displayName: 'Run Jest Tests'
      continueOnError: false
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/junit.xml'
        mergeTestResults: true
        testRunTitle: 'Unit Tests'
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()

    - script: |
        echo "📝 Documentation: Building Next.js application"
        echo Building application...
        pnpm build
      displayName: 'Build Application'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '.next'
        ArtifactName: 'next-build'
        publishLocation: 'Container'
      displayName: 'Publish Next.js Build'

- stage: Docker
  displayName: 'Docker Build and Push'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DockerBuildPush
    displayName: 'Build and Push Docker Image'
    steps:
    - checkout: self
      
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
          
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
          
    - script: |
        echo "📝 Documentation: Docker image built and pushed to registry"
        echo "Image: $(containerRegistry)/$(imageRepository):$(tag)"
        echo "Image: $(containerRegistry)/$(imageRepository):latest"
      displayName: 'Log Docker Image Details'

- stage: Deploy
  displayName: 'Continuous Deployment'
  dependsOn: Docker
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployToAzure
    displayName: 'Deploy to Azure Web App'
    steps:
    - checkout: self
    
    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppContainer'
        appName: 'system-transport-app'
        deployToSlotOrASE: true
        resourceGroupName: 'system-transport-rg'
        slotName: 'production'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'
        
    - script: |
        echo "📝 Documentation: Application deployed to Azure Web App"
        echo "App URL: https://system-transport-app.azurewebsites.net"
      displayName: 'Log Deployment Details'
      
- stage: Monitoring
  displayName: 'Monitoring and Logging'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - job: SetupMonitoring
    displayName: 'Setup Monitoring'
    steps:
    - script: |
        echo "📝 Documentation: Setting up monitoring and logging"
        echo "Setting up monitoring placeholder (to be replaced with Prometheus)"
        echo "Creating monitoring configuration..."
        mkdir -p $(Build.ArtifactStagingDirectory)/monitoring
        
        echo "# Prometheus Configuration Placeholder" > $(Build.ArtifactStagingDirectory)/monitoring/prometheus.yml
        echo "scrape_configs:" >> $(Build.ArtifactStagingDirectory)/monitoring/prometheus.yml
        echo "  - job_name: 'system-transport'" >> $(Build.ArtifactStagingDirectory)/monitoring/prometheus.yml
        echo "    static_configs:" >> $(Build.ArtifactStagingDirectory)/monitoring/prometheus.yml
        echo "      - targets: ['system-transport-app:3000']" >> $(Build.ArtifactStagingDirectory)/monitoring/prometheus.yml
        
        echo "# Logging Configuration Placeholder" > $(Build.ArtifactStagingDirectory)/monitoring/logging.yml
        echo "Application deployed and ready for monitoring setup"
      displayName: 'Configure Monitoring'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/monitoring'
        ArtifactName: 'monitoring-config'
        publishLocation: 'Container'
      displayName: 'Publish Monitoring Configuration'

- stage: Documentation
  displayName: 'Pipeline Documentation'
  dependsOn: []
  condition: succeeded()
  jobs:
  - job: GenerateDocumentation
    displayName: 'Generate Pipeline Documentation'
    steps:
    - script: |
        echo "📚 System Transport CI/CD Pipeline Documentation"
        echo "================================================"
        echo ""
        echo "This pipeline performs the following steps:"
        echo "1. 🔍 Linting: ESLint is used to ensure code quality"
        echo "2. 🧪 Testing: Jest unit tests are executed"
        echo "3. 🏗️ Building: Next.js application is built"
        echo "4. 🐳 Docker: Application is containerized and image pushed to registry"
        echo "5. 🚀 Deployment: Continuous deployment to Azure Web App"
        echo "6. 📊 Monitoring: Placeholder for Prometheus monitoring setup"
        echo ""
        echo "Pipeline last updated: $(date)"
      displayName: 'Generate Documentation'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'
        ArtifactName: 'pipeline-documentation'
        publishLocation: 'Container'
      displayName: 'Publish Documentation'
      enabled: false  # Disabled as this is just for demonstration